global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'hasura_app'

rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets:
      - localhost:9090

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
    - targets:
      - node-exporter:9100